# Generated by Django 5.1.7 on 2025-03-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='shorturl',
            name='shortener_s_short_c_a8767f_idx',
        ),
        migrations.RemoveIndex(
            model_name='shorturl',
            name='shortener_s_created_96ea04_idx',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
